### ISSUE TITLE
Status of this project and PyPI use

### ISSUE THREAD

**Issue by nim65s** [dustinlacewell/pin#4]
Hi @dustinlacewell ,

I was wondering if this project is still actively used.

I am a member of the https://github.com/stack-of-tasks/pinocchio/ project which nicknames to `pin`.
We provide releases for this project in various ecosystems, as AUR, conda, homebrew, robotpkg, and ROS.

I also have some wheels ready to be published, but the `pinocchio`name is not available, so I was looking for other candidates, and `pin` is really good one :)

Since the latest release here is from almost exactly 10 years ago, could you consider archiving this project, and releasing the "pin" name on PyPI, or do you plan to keep using it ?

Thanks :)

**Comment by nim65s** [comment]
Hello,

The 0.1rc1 release is now more than 10 years old.
Any news about this issue ?

**Comment by dustinlacewell** [comment]
I released the pin project on pypi. Good luck. :)

**Comment by nim65s** [comment]
Thanks a lot !
